In [2]:
Books=["DS with Python","BA with python"]
Books

['DS with Python', 'BA with python']

In [3]:
books=["DS with Python","BA with Python"]
books

['DS with Python', 'BA with Python']

In [4]:
b2ooks=["DS with python","BA with python"]
b2ooks

['DS with python', 'BA with python']

In [5]:
books+lists=["DS with Python","BA with Python"]
books+lists

SyntaxError: cannot assign to operator (2860965051.py, line 1)

In [6]:
books_lists=["DS with Python"],["BA with Python"]
books_lists

(['DS with Python'], ['BA with Python'])

In [7]:
books_lists=["DS with Python","BA with Python"]
books_lists

['DS with Python', 'BA with Python']

In [8]:
_books["DS with Python","BA with Python"]
_books

NameError: name '_books' is not defined

In [9]:
_books=["DS with Python","BA with Python"]
_books

['DS with Python', 'BA with Python']

In [ ]:
Data Structures
list-> elements are seperated by comma and enclosed with square bracket
Heterogenous
List can retrived using index
mutable

Types ofAnalystics
1) descriptive->past
2) diagnostic->why
3)predictive->future
4)prespective->solution

In [10]:
sample_list=[1,13,6,"hi",12,1]
sample_list

[1, 13, 6, 'hi', 12, 1]

In [11]:
type(sample_list)

list

In [12]:
sample_list[0]

1

In [13]:
sample_list[10]

IndexError: list index out of range

In [14]:
sample_list[-2]

12

In [15]:
sample_list[1]

13

In [18]:
sample_list[5]

1

In [19]:
sample_list[5]

1

In [20]:
sample_list[0]=10

In [22]:
sample_list

[10, 13, 6, 'hi', 12, 1]

In [ ]:
TUPLE
Heterogenous
Paranthesis
can retrieve dta using index
immutable

In [23]:
sample_tuple=(1,13,6,"hi",12,1)
sample_tuple

(1, 13, 6, 'hi', 12, 1)

In [24]:
type(sample_tuple)

tuple

In [25]:
sample_tuple=1,13,6,"hi",12,1
type(sample_tuple)

tuple

In [26]:
sample_tuple[-4]

6

In [27]:
sample_tuple[0]

1

In [28]:
sample_tuple[1]

13

In [29]:
sample_tuple[0]=10

TypeError: 'tuple' object does not support item assignment

In [ ]:
SET
doesnot allow duplicate
orderd-first place
in set,elements cannot be retrieved using index
set is mutable


In [30]:
sample_set={1,13.6,"hi",12,1,127,25,25,"apple","king","ball"}
sample_set

{1, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [31]:
sample_set[1]

TypeError: 'set' object is not subscriptable

In [33]:
sample_set[0]="hello"

TypeError: 'set' object does not support item assignment

In [36]:
sample_set.add(1000)

In [32]:
sample_set[0]

TypeError: 'set' object is not subscriptable

In [37]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'hi', 'king'}

In [38]:
sample_set.remove("hi")

In [39]:
sample_set

{1, 1000, 12, 127, 13.6, 25, 'apple', 'ball', 'king'}

In [ ]:
DICTIONARY
has key-value pair data structer
key is unique
values can be duplicate
values can be retrieved using key
key  cannot be retrievd using value

In [40]:
sample_dict={1:"apple",2:35.4,3:"data",2:"every",6:35.4,2:"hi"}
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4}

In [41]:
sample_dict[2]

'hi'

In [42]:
sample_dict["apple"]

KeyError: 'apple'

In [43]:
sample_dict[7]=100

In [44]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100}

In [45]:
sample_dict[10]="Business"

In [46]:
sample_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100, 10: 'Business'}

In [ ]:
numpy:package for multidimensional array

In [47]:
import numpy as np

In [48]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [50]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [53]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [56]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [60]:
###creatt an array of zeros with 2 row and 10 columns
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [62]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])